kind: Secret
apiVersion: v1
metadata:
  name: vault-kv-secret-multi
  namespace: default
type: Opaque
stringData:
  username-A: <path:kv2-a/data/test/myapp/config#username>    # vault secret path1: kv2-a 사용
  username-B: <path:kv2-b/data/test/myapp/config#username#1>    # vault secret path2: kv2-b 사용
