apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-kv-config
  namespace: default
  annotations:
    avp.kubernetes.io/path: "secret/data/myapp/config"
data:
  # 속성과 비슷한 키; 각 키는 간단한 값으로 매핑됨
  username: <username>
  password: <password>

  # 파일과 비슷한 키
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  vault.properties: |
    username=<username>
    password=<password>
