apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-kv-config
  namespace: default
data:
  vault.properties: |
    username_A=<path:kv2-a/data/test/myapp/config#username>   
    password_A=<path:kv2-a/data/test/myapp/config#password>
    username_B=<path:kv2-b/data/test/myapp/config#username>   
    password_B=<path:kv2-b/data/test/myapp/config#password>
