apiVersion: v1
kind: Pod
metadata:
  name: vault-kv-pod
  namespace: default
spec:
  serviceAccountName: default
  
  volumes:
    - name: config-volume
      configMap:
        name: vault-kv-config
        items:
        - key: "vault.properties"
          path: "myapp_config"
      
  containers:
    - name: vault-kv
      image: alpine
      command: ["sleep","infinity"]
      volumeMounts:
      - name: config-volume
        mountPath: "/etc/config"
        readOnly: true
